import { Elysia, t } from "elysia";
import { ofetch } from "ofetch";
import { injectPlugin, renderQuery } from "@/plugins";
import type { Data } from "@/types";
import { InvalidOverrideJsonError, UnionFeedError, parse, union } from "@/utils";

export default new Elysia({
	detail: {
		description: `
Merge multiple RSS/Atom feeds into a single feed.

Returns all unique items from the provided feeds, removing duplicates based on item ID. If item has no ID, title or link is used for deduplication.
`,
	},
	name: "RSSBook/Router/Utils/Union",
	prefix: "/union",
})
	.use(injectPlugin)
	.get(
		"/",
		async ({ query: { feeds, override }, logger }) => {
			if (feeds.length < 2) {
				throw new UnionFeedError("At least 2 feeds are required for union");
			}

			const promises = feeds.map(async (feedUrl) => {
				try {
					const response = await ofetch(feedUrl, { responseType: "text" });
					return parse(response);
				} catch (error) {
					logger.error(`Failed to fetch or parse feed from ${feedUrl}: ${error}`);
					return null;
				}
			});

			const results = await Promise.allSettled(promises);
			const datas: Data[] = results
				.filter(
					(result): result is PromiseFulfilledResult<Data | null> => result.status === "fulfilled",
				)
				.map((result) => result.value)
				.filter((result): result is Data => result !== null);

			const [firstData, ...restData] = datas;
			const unionedData = union(firstData, restData);

			// Parse override if provided
			let overrideData: Partial<Omit<Data, "item">> | undefined;
			if (override) {
				try {
					overrideData = JSON.parse(override);
				} catch (error) {
					throw new InvalidOverrideJsonError(
						`Invalid override JSON: ${error instanceof Error ? error.message : String(error)}`,
						error,
					);
				}
			}

			return {
				...unionedData,
				...overrideData,
			} satisfies Data;
		},
		{
			query: t.Object({
				feeds: t.Array(
					t.String({
						format: "uri",
					}),
					{
						examples: ["https://www.ruanyifeng.com/blog/atom.xml,https://www.zhihu.com/rss"],
						title: "Feed URLs Array",
					},
				),

				override: t.Optional(
					t.String({
						description: "Override feed metadata (JSON string)",
						examples: [
							JSON.stringify({
								description: "A combined feed from multiple sources, generated by RSSBook.",
								language: "zh-CN",
								title: "Union Feed",
							}),
						],
					}),
				),

				...renderQuery,
			}),
		},
	);
